name: olympics
dependencies:
  - python>=3.6
  - numpy
  - matplotlib
  - pandas
  - scikit-learn
  - seaborn
  - mpld3
  - cython
  - flask
  - pip
  - gunicorn
  - pip:
    - jupyter
    - nbdime
    - xlwt
    - inflection
